/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carwash;

import java.beans.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author JAGUAR
 */
public class AddAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AddAdmin
     */
    public AddAdmin() {
        initComponents();
        ImageIcon icon = new ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\CARWASH\\src\\carwash\\car.png");
        setIconImage(icon.getImage());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddAdmin = new javax.swing.JButton();
        pfConfirmPasswordAdmin = new com.raven.swing.PasswordField();
        tfAddressAdmin = new com.raven.swing.TextField();
        pfPasswordAdmin = new com.raven.swing.PasswordField();
        btnCancel = new javax.swing.JButton();
        tfPhoneAdmin = new com.raven.swing.TextField();
        tfEmailAdmin = new com.raven.swing.TextField();
        tfNameAdmin = new com.raven.swing.TextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(761, 386));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(761, 420));
        jPanel1.setPreferredSize(new java.awt.Dimension(761, 420));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddAdmin.setBackground(new java.awt.Color(45, 21, 203));
        btnAddAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAdmin.setText("Add");
        btnAddAdmin.setFocusable(false);
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 90, 30));

        pfConfirmPasswordAdmin.setLabelText("Confirm Password");
        pfConfirmPasswordAdmin.setLineColor(new java.awt.Color(131, 126, 253));
        pfConfirmPasswordAdmin.setSelectionColor(new java.awt.Color(157, 153, 255));
        pfConfirmPasswordAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfConfirmPasswordAdminActionPerformed(evt);
            }
        });
        jPanel1.add(pfConfirmPasswordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 310, -1));

        tfAddressAdmin.setLabelText("Address");
        tfAddressAdmin.setLineColor(new java.awt.Color(131, 126, 253));
        tfAddressAdmin.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfAddressAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressAdminActionPerformed(evt);
            }
        });
        jPanel1.add(tfAddressAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 310, 60));

        pfPasswordAdmin.setLabelText("Password");
        pfPasswordAdmin.setLineColor(new java.awt.Color(131, 126, 253));
        pfPasswordAdmin.setSelectionColor(new java.awt.Color(157, 153, 255));
        pfPasswordAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordAdminActionPerformed(evt);
            }
        });
        jPanel1.add(pfPasswordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 310, -1));

        btnCancel.setBackground(new java.awt.Color(45, 21, 203));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setFocusable(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 80, 30));

        tfPhoneAdmin.setLabelText("Phone");
        tfPhoneAdmin.setLineColor(new java.awt.Color(131, 126, 253));
        tfPhoneAdmin.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfPhoneAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneAdminActionPerformed(evt);
            }
        });
        jPanel1.add(tfPhoneAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 310, 60));

        tfEmailAdmin.setLineColor(new java.awt.Color(131, 126, 253));
        tfEmailAdmin.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfEmailAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailAdminActionPerformed(evt);
            }
        });
        jPanel1.add(tfEmailAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 310, 60));

        tfNameAdmin.setLabelText("Name\n");
        tfNameAdmin.setLineColor(new java.awt.Color(131, 126, 253));
        tfNameAdmin.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfNameAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameAdminActionPerformed(evt);
            }
        });
        jPanel1.add(tfNameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 310, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carwash/images/add admin 720 387.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 721, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameAdminActionPerformed

    private void tfAddressAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressAdminActionPerformed

    private void tfEmailAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailAdminActionPerformed

    private void tfPhoneAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneAdminActionPerformed

    private void pfPasswordAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordAdminActionPerformed

    private void pfConfirmPasswordAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfConfirmPasswordAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfConfirmPasswordAdminActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        String name = tfNameAdmin.getText();
        String email = tfEmailAdmin.getText();
        String phone = tfPhoneAdmin.getText();
        String address = tfAddressAdmin.getText();
        String password = String.valueOf(pfPasswordAdmin.getPassword());
        String confirmPassword = String.valueOf(pfConfirmPasswordAdmin.getPassword());

        if(name.isEmpty()||email.isEmpty()||phone.isEmpty()||address.isEmpty()||password.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter all field ","try again ",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(password.equals(confirmPassword)){
            try{
                java.sql.Statement stmt = DbConnection.myconn().createStatement();
                stmt.executeUpdate("INSERT INTO admin(admin_name,admin_email,phone,address,password)"+"VALUES('"+name+"','"+email+"','"+phone+"','"+address+"','"+password+"')");

                //JOptionPane.showMessageDialog(rootPane, "Your account created.Login now ");
                test.Message me = new test.Message(this, true);
                me.showAlert();
                
                this.dispose();
                new AdminLogIn().setVisible(true);
                //new DashBoard(email,null,null).setVisible(true);

            }catch(Exception e){
                System.out.println(e);

            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Passwords do not match,Please try again ");
        }
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
        new FirstPage().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.raven.swing.PasswordField pfConfirmPasswordAdmin;
    private com.raven.swing.PasswordField pfPasswordAdmin;
    private com.raven.swing.TextField tfAddressAdmin;
    private com.raven.swing.TextField tfEmailAdmin;
    private com.raven.swing.TextField tfNameAdmin;
    private com.raven.swing.TextField tfPhoneAdmin;
    // End of variables declaration//GEN-END:variables
}
