/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carwash;
import com.raven.datechooser.SelectedDate;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Statement;

/**
 *
 * @author JAGUAR
 */
public class AddVehicle extends javax.swing.JFrame {
    Connection con  = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String UserID=null;
    String email= null;
    String branchName= null;
    //String userID="123";
    /**
     * Creates new form AddVehicle
     * @param email
     * @param UserID
     */
    public AddVehicle(String email,String UserID,String branchName) {
        initComponents();
        this.UserID=UserID;
        this.email=email;
        this.branchName=email;
        con = DbConnection.myconn();
        ImageIcon icon = new ImageIcon("C:\\Users\\JAGUAR\\Documents\\GitHub\\Car-wash-application-dextop\\CARWASH_QR_Update\\src\\carwash\\car.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser = new com.raven.datechooser.DateChooser();
        dateDate = new javax.swing.JTextField();
        tfVehicleType = new javax.swing.JComboBox<>();
        tfVehicleName = new javax.swing.JTextField();
        REGISTER = new javax.swing.JLabel();
        tfVehicleNo = new javax.swing.JTextField();
        tfEngineNo = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jDateChooser.setForeground(new java.awt.Color(0, 51, 204));
        jDateChooser.setTextRefernce(dateDate);
        jDateChooser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDateChooserAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateDateMouseClicked(evt);
            }
        });
        getContentPane().add(dateDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 290, 30));

        tfVehicleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High Weight Vehicle", "Low Weight Vehicle" }));
        getContentPane().add(tfVehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 290, 30));

        tfVehicleName.setText("  Vehicle Name");
        tfVehicleName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfVehicleName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfVehicleNameFocusLost(evt);
            }
        });
        tfVehicleName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfVehicleNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfVehicleNameMouseEntered(evt);
            }
        });
        tfVehicleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVehicleNameActionPerformed(evt);
            }
        });
        tfVehicleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfVehicleNameKeyPressed(evt);
            }
        });
        getContentPane().add(tfVehicleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 290, 30));

        REGISTER.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        REGISTER.setText("Add Vehicle");
        getContentPane().add(REGISTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 190, 30));

        tfVehicleNo.setText("  Vehicle No");
        tfVehicleNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfVehicleNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfVehicleNoFocusLost(evt);
            }
        });
        tfVehicleNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfVehicleNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfVehicleNoMouseEntered(evt);
            }
        });
        tfVehicleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVehicleNoActionPerformed(evt);
            }
        });
        tfVehicleNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfVehicleNoKeyPressed(evt);
            }
        });
        getContentPane().add(tfVehicleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 290, 30));

        tfEngineNo.setText("  Engine No");
        tfEngineNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfEngineNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEngineNoFocusLost(evt);
            }
        });
        tfEngineNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEngineNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfEngineNoMouseEntered(evt);
            }
        });
        tfEngineNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEngineNoKeyPressed(evt);
            }
        });
        getContentPane().add(tfEngineNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 290, 30));

        btnAdd.setBackground(new java.awt.Color(45, 21, 203));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setFocusable(false);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 90, 30));

        btnCancel.setBackground(new java.awt.Color(45, 21, 203));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setFocusable(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carwash/images/addvehicle1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 721, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfVehicleNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfVehicleNameFocusLost
        if (tfVehicleName.getText().isEmpty()) {
            tfVehicleName.setText("Vehicle Name");
        }
    }//GEN-LAST:event_tfVehicleNameFocusLost

    private void tfVehicleNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfVehicleNameMouseClicked
        tfVehicleName.setText("");
    }//GEN-LAST:event_tfVehicleNameMouseClicked

    private void tfVehicleNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfVehicleNameMouseEntered

    }//GEN-LAST:event_tfVehicleNameMouseEntered

    private void tfVehicleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVehicleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVehicleNameActionPerformed

    private void tfVehicleNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVehicleNameKeyPressed
        tfVehicleName.requestFocusInWindow();
    }//GEN-LAST:event_tfVehicleNameKeyPressed

    private void tfVehicleNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfVehicleNoFocusLost
        if (tfVehicleNo.getText().isEmpty()) {
            tfVehicleNo.setText("Vehicle_No");
        }
    }//GEN-LAST:event_tfVehicleNoFocusLost

    private void tfVehicleNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfVehicleNoMouseClicked
        tfVehicleNo.setText("");
    }//GEN-LAST:event_tfVehicleNoMouseClicked

    private void tfVehicleNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfVehicleNoMouseEntered

    }//GEN-LAST:event_tfVehicleNoMouseEntered

    private void tfVehicleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVehicleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVehicleNoActionPerformed

    private void tfVehicleNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVehicleNoKeyPressed
        tfVehicleNo.requestFocusInWindow();
    }//GEN-LAST:event_tfVehicleNoKeyPressed

    private void tfEngineNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEngineNoFocusLost
        if (tfEngineNo.getText().isEmpty()) {
            tfEngineNo.setText("Engine_No");
        }
    }//GEN-LAST:event_tfEngineNoFocusLost

    private void tfEngineNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEngineNoMouseClicked
        tfEngineNo.setText("");
    }//GEN-LAST:event_tfEngineNoMouseClicked

    private void tfEngineNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEngineNoMouseEntered

    }//GEN-LAST:event_tfEngineNoMouseEntered

    private void tfEngineNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEngineNoKeyPressed
        tfEngineNo.requestFocusInWindow();
    }//GEN-LAST:event_tfEngineNoKeyPressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //String str = "abc";
        
        String Vehicle_name = tfVehicleName.getText();
        String Vehicle_No = tfVehicleNo.getText();
        Object vehicle_Type1 = tfVehicleType.getSelectedItem();
        String vehicle_Type = vehicle_Type1.toString();
        String engine_no = tfEngineNo.getText();
        //JDateChooser dateChooser = new JDateChooser();
        SelectedDate d = jDateChooser.getSelectedDate();
        String date= d.getYear()+"-"+d.getMonth()+"-"+d.getDay();
        
        

        if(Vehicle_name.isEmpty()||Vehicle_No.isEmpty()||vehicle_Type.isEmpty()||engine_no.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter all field ","try again ",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
            try{
                Statement stmt = DbConnection.myconn().createStatement();
            //String UserID = null;
            //String str = "123";
                String userId1= UserID;
                stmt.executeUpdate("INSERT INTO vehicles(customer_id,vehicle_name,vehicle_no,vehicle_type,engine_no,last_washed_date)"+"VALUES('"+userId1+"','"+Vehicle_name+"','"+Vehicle_No+"','"+vehicle_Type+"','"+engine_no+"','"+date+"')");

                JOptionPane.showMessageDialog(rootPane, "Record added, Press OK ");
                dispose();
                new DashBoard(email,UserID,branchName).setVisible(true);

            }catch(Exception e){
                System.out.println(e);

            }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
        //new FirstPage().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    private void dateDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateDateMouseClicked
        jDateChooser.setVisible(true);
    }//GEN-LAST:event_dateDateMouseClicked

    private void jDateChooserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooserAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVehicle(null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel REGISTER;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTextField dateDate;
    private com.raven.datechooser.DateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfEngineNo;
    private javax.swing.JTextField tfVehicleName;
    private javax.swing.JTextField tfVehicleNo;
    private javax.swing.JComboBox<String> tfVehicleType;
    // End of variables declaration//GEN-END:variables
}
