
package carwash;

import com.raven.chart.ModelChart;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javaswingdev.chart.ModelPieChart;
import javaswingdev.chart.PieChart;
import javaswingdev.message.MessageDialog;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hashan
 */
public class AdminPanel extends javax.swing.JFrame {

    String branch_id=null;
    Connection con  = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private boolean isDataAdded = false;
    
    public AdminPanel() {
        initComponents();
        ImageIcon icon = new ImageIcon("C:\\Users\\hashan\\OneDrive\\Desktop\\CARWASH_Dash_himal\\CARWASH_Dash_Updated\\src\\carwash\\images\\car.png");
        setIconImage(icon.getImage());
        con = DbConnection.myconn();
        getContentPane().setBackground(new Color(250, 250, 250));
        chart1.addLegend("Income", new Color(245, 189, 135));
        chart1.addLegend("Expense", new Color(135, 189, 245));
        chart1.addLegend("Profit", new Color(189, 135, 245));
        chart1.addLegend("cost", new Color(139, 229, 222));
        Color[] colors = {new Color(23, 126, 238), new Color(221, 65, 65), new Color(47, 157, 64), new Color(196, 151, 58)};
        try {
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/analysis", "root","");
            //stmt = con.createStatement();
            String sql = "SELECT * FROM monthly_analysis";
            //ResultSet rs = stmt.executeQuery("SELECT * FROM mytable");
            pst = con.prepareCall(sql);
           
            rs = pst.executeQuery();
            while (rs.next()) {
                String month = rs.getString("month");
                double income = rs.getDouble("income");
                double expense = rs.getDouble("expense");
                double profit = rs.getDouble("profit");
                double cost = rs.getDouble("cost");
                
                chart1.addData(new ModelChart(month, new double[]{income, expense, profit, cost}));
            }
            String sql2 = "SELECT * FROM branch_analysis";
            pst = con.prepareCall(sql2);
           
            rs = pst.executeQuery();
            int colorIndex = 0;
            while (rs.next()) {
                String district = rs.getString("district");
                double count = rs.getDouble("customercount");
                pieChart1.setChartType(PieChart.PeiChartType. DEFAULT);
                pieChart1.addData(new ModelPieChart(district, count, colors[colorIndex % colors.length]));
                colorIndex++;
                //pieChart1.addData(new ModelPieChart("Kady", 120, new Color(221, 65, 65)));
                //pieChart1.addData(new ModelPieChart("Jaffna", 20, new Color(47, 157, 64)));
               // pieChart1.addData(new ModelPieChart("Anuradhapura", 60, new Color(196, 151, 58)));
                
                //chart1.addData(new ModelChart(month, new double[]{income, expense, profit, cost}));
            }
            
            /*rs.close();
            stmt.close();
            con.close();*/
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        dateChooser2 = new com.raven.datechooser.DateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanelInvoice = new javax.swing.JPanel();
        jPanelAddBranch = new javax.swing.JPanel();
        jPanelRemoveBranch = new javax.swing.JPanel();
        jPanelAnalytics = new javax.swing.JPanel();
        pieChart1 = new javaswingdev.chart.PieChart();
        chart1 = new com.raven.chart.Chart();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelVehicleTypes = new javax.swing.JPanel();
        jPanelInquiries = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfInquiryID = new com.raven.swing.TextField();
        tfName2 = new com.raven.swing.TextField();
        tfMsgTitle = new com.raven.swing.TextField();
        tfMsgContent = new com.raven.swing.TextField();
        tfEmail2 = new com.raven.swing.TextField();
        jPanelInquiryReply = new javax.swing.JPanel();
        tfUserInquiryID = new com.raven.swing.TextField();
        tfAdminResponse = new com.raven.swing.TextField();
        btnCancel = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        jPanelOnGoingServices = new javax.swing.JPanel();
        jPanelHelp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        btnInvoice = new javax.swing.JButton();
        btnAddAdmin = new javax.swing.JButton();
        btnAddbranch = new javax.swing.JButton();
        btnRemoveBranch = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();
        btnVehicaltype = new javax.swing.JButton();
        btnInquiries = new javax.swing.JButton();
        btnInqueryReply = new javax.swing.JButton();
        btnOnGoingServices = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        jTextFieldToDate = new javax.swing.JTextField();
        jTextFieldFromDate = new javax.swing.JTextField();
        jTextFieldBranchId = new javax.swing.JTextField();
        mainbg1 = new javax.swing.JLabel();

        dateChooser1.setForeground(new java.awt.Color(45, 21, 203));
        dateChooser1.setTextRefernce(jTextFieldFromDate);

        dateChooser2.setForeground(new java.awt.Color(45, 21, 203));
        dateChooser2.setTextRefernce(jTextFieldToDate);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInvoice.setBackground(new java.awt.Color(255, 51, 255));

        javax.swing.GroupLayout jPanelInvoiceLayout = new javax.swing.GroupLayout(jPanelInvoice);
        jPanelInvoice.setLayout(jPanelInvoiceLayout);
        jPanelInvoiceLayout.setHorizontalGroup(
            jPanelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanelInvoiceLayout.setVerticalGroup(
            jPanelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelAddBranch.setBackground(new java.awt.Color(102, 255, 51));

        javax.swing.GroupLayout jPanelAddBranchLayout = new javax.swing.GroupLayout(jPanelAddBranch);
        jPanelAddBranch.setLayout(jPanelAddBranchLayout);
        jPanelAddBranchLayout.setHorizontalGroup(
            jPanelAddBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanelAddBranchLayout.setVerticalGroup(
            jPanelAddBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelAddBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelRemoveBranch.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanelRemoveBranchLayout = new javax.swing.GroupLayout(jPanelRemoveBranch);
        jPanelRemoveBranch.setLayout(jPanelRemoveBranchLayout);
        jPanelRemoveBranchLayout.setHorizontalGroup(
            jPanelRemoveBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanelRemoveBranchLayout.setVerticalGroup(
            jPanelRemoveBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelRemoveBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelAnalytics.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Branch Analysis");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Monthly Analysis");

        javax.swing.GroupLayout jPanelAnalyticsLayout = new javax.swing.GroupLayout(jPanelAnalytics);
        jPanelAnalytics.setLayout(jPanelAnalyticsLayout);
        jPanelAnalyticsLayout.setHorizontalGroup(
            jPanelAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnalyticsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(pieChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnalyticsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(jPanelAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAnalyticsLayout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(514, Short.MAX_VALUE)))
        );
        jPanelAnalyticsLayout.setVerticalGroup(
            jPanelAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAnalyticsLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chart1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(pieChart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
            .addGroup(jPanelAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAnalyticsLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(357, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanelAnalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelVehicleTypes.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanelVehicleTypesLayout = new javax.swing.GroupLayout(jPanelVehicleTypes);
        jPanelVehicleTypes.setLayout(jPanelVehicleTypesLayout);
        jPanelVehicleTypesLayout.setHorizontalGroup(
            jPanelVehicleTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanelVehicleTypesLayout.setVerticalGroup(
            jPanelVehicleTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelVehicleTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelInquiries.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inquiry ID", "Name", "Email", "Message Title", "Message Content"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tfInquiryID.setLabelText("Inquiry ID");
        tfInquiryID.setLineColor(new java.awt.Color(131, 126, 253));
        tfInquiryID.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfInquiryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInquiryIDActionPerformed(evt);
            }
        });

        tfName2.setLabelText("Name");
        tfName2.setLineColor(new java.awt.Color(131, 126, 253));
        tfName2.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfName2ActionPerformed(evt);
            }
        });

        tfMsgTitle.setLabelText("Message Title");
        tfMsgTitle.setLineColor(new java.awt.Color(131, 126, 253));
        tfMsgTitle.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfMsgTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMsgTitleActionPerformed(evt);
            }
        });

        tfMsgContent.setLabelText("Message Content");
        tfMsgContent.setLineColor(new java.awt.Color(131, 126, 253));
        tfMsgContent.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfMsgContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMsgContentActionPerformed(evt);
            }
        });

        tfEmail2.setLabelText("Name");
        tfEmail2.setLineColor(new java.awt.Color(131, 126, 253));
        tfEmail2.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfEmail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmail2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInquiriesLayout = new javax.swing.GroupLayout(jPanelInquiries);
        jPanelInquiries.setLayout(jPanelInquiriesLayout);
        jPanelInquiriesLayout.setHorizontalGroup(
            jPanelInquiriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInquiriesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelInquiriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInquiriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInquiriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfInquiryID, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfMsgTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfEmail2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfMsgContent, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanelInquiriesLayout.setVerticalGroup(
            jPanelInquiriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInquiriesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelInquiriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInquiriesLayout.createSequentialGroup()
                        .addComponent(tfInquiryID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfName2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(tfMsgTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfMsgContent, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelInquiries, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelInquiryReply.setBackground(new java.awt.Color(255, 255, 255));

        tfUserInquiryID.setLabelText("User Inquiry ID");
        tfUserInquiryID.setLineColor(new java.awt.Color(131, 126, 253));
        tfUserInquiryID.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfUserInquiryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserInquiryIDActionPerformed(evt);
            }
        });

        tfAdminResponse.setLabelText("Admin Response");
        tfAdminResponse.setLineColor(new java.awt.Color(131, 126, 253));
        tfAdminResponse.setSelectionColor(new java.awt.Color(157, 153, 255));
        tfAdminResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAdminResponseActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(45, 21, 203));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSend.setBackground(new java.awt.Color(45, 21, 203));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInquiryReplyLayout = new javax.swing.GroupLayout(jPanelInquiryReply);
        jPanelInquiryReply.setLayout(jPanelInquiryReplyLayout);
        jPanelInquiryReplyLayout.setHorizontalGroup(
            jPanelInquiryReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInquiryReplyLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(jPanelInquiryReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAdminResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUserInquiryID, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInquiryReplyLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(jPanelInquiryReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInquiryReplyLayout.createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(489, Short.MAX_VALUE)))
        );
        jPanelInquiryReplyLayout.setVerticalGroup(
            jPanelInquiryReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInquiryReplyLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(tfUserInquiryID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfAdminResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(jPanelInquiryReplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInquiryReplyLayout.createSequentialGroup()
                    .addContainerGap(349, Short.MAX_VALUE)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(100, 100, 100)))
        );

        jPanel2.add(jPanelInquiryReply, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelOnGoingServices.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanelOnGoingServicesLayout = new javax.swing.GroupLayout(jPanelOnGoingServices);
        jPanelOnGoingServices.setLayout(jPanelOnGoingServicesLayout);
        jPanelOnGoingServicesLayout.setHorizontalGroup(
            jPanelOnGoingServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanelOnGoingServicesLayout.setVerticalGroup(
            jPanelOnGoingServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelOnGoingServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 480));

        javax.swing.GroupLayout jPanelHelpLayout = new javax.swing.GroupLayout(jPanelHelp);
        jPanelHelp.setLayout(jPanelHelpLayout);
        jPanelHelpLayout.setHorizontalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );
        jPanelHelpLayout.setVerticalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 129, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setText("Date :");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 616, 80, 20));

        time.setText("Time :");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 616, 80, 20));

        btnInvoice.setBackground(new java.awt.Color(45, 21, 203));
        btnInvoice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnInvoice.setForeground(new java.awt.Color(255, 255, 255));
        btnInvoice.setText("Invoice");
        btnInvoice.setOpaque(true);
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(btnInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, 40));

        btnAddAdmin.setBackground(new java.awt.Color(45, 21, 203));
        btnAddAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAdmin.setText("Add Admin");
        btnAddAdmin.setOpaque(true);
        btnAddAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAdminMouseClicked(evt);
            }
        });
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 270, 30));

        btnAddbranch.setBackground(new java.awt.Color(45, 21, 203));
        btnAddbranch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddbranch.setForeground(new java.awt.Color(255, 255, 255));
        btnAddbranch.setText("Add Branch");
        btnAddbranch.setOpaque(true);
        btnAddbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddbranchActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 270, 30));

        btnRemoveBranch.setBackground(new java.awt.Color(45, 21, 203));
        btnRemoveBranch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRemoveBranch.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveBranch.setText("Remove Branch");
        btnRemoveBranch.setOpaque(true);
        btnRemoveBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBranchActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoveBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 270, 30));

        btnLogout.setBackground(new java.awt.Color(45, 21, 203));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setOpaque(true);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 270, 30));

        btnAnalytics.setBackground(new java.awt.Color(45, 21, 203));
        btnAnalytics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        btnAnalytics.setText("Analytics");
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 110, 30));

        btnVehicaltype.setBackground(new java.awt.Color(45, 21, 203));
        btnVehicaltype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVehicaltype.setForeground(new java.awt.Color(255, 255, 255));
        btnVehicaltype.setText("Vehical Types");
        btnVehicaltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicaltypeActionPerformed(evt);
            }
        });
        jPanel1.add(btnVehicaltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 130, 30));

        btnInquiries.setBackground(new java.awt.Color(45, 21, 203));
        btnInquiries.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInquiries.setForeground(new java.awt.Color(255, 255, 255));
        btnInquiries.setText("Inquiries");
        btnInquiries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInquiriesMouseClicked(evt);
            }
        });
        btnInquiries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInquiriesActionPerformed(evt);
            }
        });
        jPanel1.add(btnInquiries, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 20, 120, 30));

        btnInqueryReply.setBackground(new java.awt.Color(45, 21, 203));
        btnInqueryReply.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInqueryReply.setForeground(new java.awt.Color(255, 255, 255));
        btnInqueryReply.setText("Inquery Reply");
        btnInqueryReply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInqueryReplyMouseClicked(evt);
            }
        });
        btnInqueryReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInqueryReplyActionPerformed(evt);
            }
        });
        jPanel1.add(btnInqueryReply, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 20, 140, 30));

        btnOnGoingServices.setBackground(new java.awt.Color(45, 21, 203));
        btnOnGoingServices.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOnGoingServices.setForeground(new java.awt.Color(255, 255, 255));
        btnOnGoingServices.setText("On Going Services");
        btnOnGoingServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnGoingServicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnOnGoingServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 20, 160, 30));

        btnHelp.setBackground(new java.awt.Color(45, 21, 203));
        btnHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(255, 255, 255));
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 110, 30));

        jTextFieldToDate.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "To"));
        jPanel1.add(jTextFieldToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 270, 40));

        jTextFieldFromDate.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "From"));
        jTextFieldFromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFromDateActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 270, 40));

        jTextFieldBranchId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldBranchId.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Branch ID"));
        jPanel1.add(jTextFieldBranchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 270, 40));

        mainbg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carwash/images/adminpanel1.png"))); // NOI18N
        mainbg1.setText("jLabel1");
        jPanel1.add(mainbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1243, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
        jPanelInvoice.setVisible(true);
        jPanelAddBranch.setVisible(false);
        jPanelRemoveBranch.setVisible(false);
        jPanelAnalytics.setVisible(false);
        jPanelVehicleTypes.setVisible(false);
        jPanelInquiries.setVisible(false);
        jPanelInquiryReply.setVisible(false);
        jPanelOnGoingServices.setVisible(false);
        jPanelHelp.setVisible(false);
    }//GEN-LAST:event_btnInvoiceActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnAddbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddbranchActionPerformed
        jPanelInvoice.setVisible(false);
        jPanelAddBranch.setVisible(true);
        jPanelRemoveBranch.setVisible(false);
        jPanelAnalytics.setVisible(false);
        jPanelVehicleTypes.setVisible(false);
        jPanelInquiries.setVisible(false);
        jPanelInquiryReply.setVisible(false);
        jPanelOnGoingServices.setVisible(false);
        jPanelHelp.setVisible(false);
    }//GEN-LAST:event_btnAddbranchActionPerformed

    private void btnRemoveBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBranchActionPerformed
        jPanelInvoice.setVisible(false);
        jPanelAddBranch.setVisible(false);
        jPanelRemoveBranch.setVisible(true);
        jPanelAnalytics.setVisible(false);
        jPanelVehicleTypes.setVisible(false);
        jPanelInquiries.setVisible(false);
        jPanelInquiryReply.setVisible(false);
        jPanelOnGoingServices.setVisible(false);
        jPanelHelp.setVisible(false);
    }//GEN-LAST:event_btnRemoveBranchActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        MessageDialog obj = new MessageDialog(this);
        obj.showMessage("Are you leaving ?", "Are you sure want to log out? All your\nunsaved data will be lost.");
        if (obj.getMessageType() == MessageDialog.MessageType.OK) {
           // System.out.println("User click ok");
           dispose();
           FirstPage obj1 = new FirstPage();
           obj1.setVisible(true);
        } else {
            System.out.println("User click cancel");
        }
     
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        jPanelInvoice.setVisible(false);
        jPanelAddBranch.setVisible(false);
        jPanelRemoveBranch.setVisible(false);
        jPanelAnalytics.setVisible(true);
        jPanelVehicleTypes.setVisible(false);
        jPanelInquiries.setVisible(false);
        jPanelInquiryReply.setVisible(false);
        jPanelOnGoingServices.setVisible(false);
        jPanelHelp.setVisible(false);
        chart1.start();
    }//GEN-LAST:event_btnAnalyticsActionPerformed

    private void btnOnGoingServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnGoingServicesActionPerformed
        jPanelInvoice.setVisible(false);
        jPanelAddBranch.setVisible(false);
        jPanelRemoveBranch.setVisible(false);
        jPanelAnalytics.setVisible(false);
        jPanelVehicleTypes.setVisible(false);
        jPanelInquiries.setVisible(false);
        jPanelInquiryReply.setVisible(false);
        jPanelOnGoingServices.setVisible(true);
        jPanelHelp.setVisible(false);
    }//GEN-LAST:event_btnOnGoingServicesActionPerformed

    private void jTextFieldFromDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFromDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFromDateActionPerformed

    private void btnAddAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAdminMouseClicked
        //dispose();
        new AddAdmin().setVisible(true);
    }//GEN-LAST:event_btnAddAdminMouseClicked

    private void btnInquiriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInquiriesMouseClicked
        
    }//GEN-LAST:event_btnInquiriesMouseClicked

    private void btnInqueryReplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInqueryReplyMouseClicked
        
    }//GEN-LAST:event_btnInqueryReplyMouseClicked

    private void btnInquiriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInquiriesActionPerformed
        jPanelInvoice.setVisible(false);
        jPanelAddBranch.setVisible(false);
        jPanelRemoveBranch.setVisible(false);
        jPanelAnalytics.setVisible(false);
        jPanelVehicleTypes.setVisible(false);
        jPanelInquiries.setVisible(true);
        jPanelInquiryReply.setVisible(false);
        jPanelOnGoingServices.setVisible(false);
        jPanelHelp.setVisible(false);
        if (isDataAdded) {
        return;
        }
        try {
            Statement stmt = DbConnection.myconn().createStatement();
            String query = "SELECT * FROM inquiries";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
               String id = String.valueOf(rs.getInt("inquiry_id"));
               String name = rs.getString("name");
               String email = rs.getString("email");
               String message_title  = rs.getString("message_title");
               String message_content  = rs.getString("message_content");
               
               
               String tbData[] = {id,name,email,message_title,message_content};
               DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
               
               tblModel.addRow(tbData);
               
            }
            isDataAdded = true;    
        } catch (Exception e) {
                System.out.println(e);
        }
        //btnInquiries.setEnabled(false);
        
    }//GEN-LAST:event_btnInquiriesActionPerformed

    private void btnInqueryReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInqueryReplyActionPerformed
        jPanelInvoice.setVisible(false);
        jPanelAddBranch.setVisible(false);
        jPanelRemoveBranch.setVisible(false);
        jPanelAnalytics.setVisible(false);
        jPanelVehicleTypes.setVisible(false);
        jPanelInquiries.setVisible(false);
        jPanelInquiryReply.setVisible(true);
        jPanelOnGoingServices.setVisible(false);
        jPanelHelp.setVisible(false);
    }//GEN-LAST:event_btnInqueryReplyActionPerformed

    private void btnVehicaltypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicaltypeActionPerformed
        jPanelInvoice.setVisible(false);
        jPanelAddBranch.setVisible(false);
        jPanelRemoveBranch.setVisible(false);
        jPanelAnalytics.setVisible(false);
        jPanelVehicleTypes.setVisible(true);
        jPanelInquiries.setVisible(false);
        jPanelInquiryReply.setVisible(false);
        jPanelOnGoingServices.setVisible(false);
        jPanelHelp.setVisible(false);
    }//GEN-LAST:event_btnVehicaltypeActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        jPanelInvoice.setVisible(false);
        jPanelAddBranch.setVisible(false);
        jPanelRemoveBranch.setVisible(false);
        jPanelAnalytics.setVisible(false);
        jPanelVehicleTypes.setVisible(false);
        jPanelInquiries.setVisible(false);
        jPanelInquiryReply.setVisible(false);
        jPanelOnGoingServices.setVisible(false);
        jPanelHelp.setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void tfInquiryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInquiryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInquiryIDActionPerformed

    private void tfName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfName2ActionPerformed

    private void tfMsgTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMsgTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMsgTitleActionPerformed

    private void tfMsgContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMsgContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMsgContentActionPerformed

    private void tfEmail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmail2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        
        
        String tblid = tblModel.getValueAt(jTable1.getSelectedRow(),0).toString();
        String tblName = tblModel.getValueAt(jTable1.getSelectedRow(),1).toString();
        String tblEmail = tblModel.getValueAt(jTable1.getSelectedRow(),2).toString();
        String tblMessageTitle = tblModel.getValueAt(jTable1.getSelectedRow(),3).toString();
        String tblMessageContent = tblModel.getValueAt(jTable1.getSelectedRow(),4).toString();
        
        
        tfInquiryID.setText(tblid);
        tfName2.setText(tblName);
        tfEmail2.setText(tblEmail);
        tfMsgTitle.setText(tblMessageTitle);
        tfMsgContent.setText(tblMessageContent);
    }//GEN-LAST:event_jTable1MouseClicked

    private void tfUserInquiryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserInquiryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserInquiryIDActionPerformed

    private void tfAdminResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAdminResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAdminResponseActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        int inquiryID = 0;
        try {
           inquiryID = Integer.parseInt(tfUserInquiryID.getText());
        } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "Please enter a valid integer value for inquery ID.", "Invalid input", JOptionPane.ERROR_MESSAGE);
           return;
        }

        String adminReply = tfAdminResponse.getText();

        if (adminReply.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Please enter a message.", "Try again", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        try{
            Statement stmt = con.createStatement();
            // Check if the inquery ID exists in the inquiries table
            ResultSet rs = stmt.executeQuery("SELECT * FROM inquiries WHERE inquiry_ID = " + inquiryID);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "The inquiry ID does not exist.", "Invalid input", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }catch(SQLException e){
           System.err.println(e.getMessage());
        }

        try {
           Statement stmt = con.createStatement();
           String query = "INSERT INTO admin_reply (admin_response, user_inquiryID) VALUES (?, ?)";
           PreparedStatement ps = con.prepareStatement(query);
           ps.setString(1, adminReply);
           ps.setInt(2, inquiryID);
           ps.executeUpdate();

           JOptionPane.showMessageDialog(this, "Message sent successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
           System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddbranch;
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnInqueryReply;
    private javax.swing.JButton btnInquiries;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOnGoingServices;
    private javax.swing.JButton btnRemoveBranch;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnVehicaltype;
    private com.raven.chart.Chart chart1;
    private javax.swing.JLabel date;
    private com.raven.datechooser.DateChooser dateChooser1;
    private com.raven.datechooser.DateChooser dateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAddBranch;
    private javax.swing.JPanel jPanelAnalytics;
    private javax.swing.JPanel jPanelHelp;
    private javax.swing.JPanel jPanelInquiries;
    private javax.swing.JPanel jPanelInquiryReply;
    private javax.swing.JPanel jPanelInvoice;
    private javax.swing.JPanel jPanelOnGoingServices;
    private javax.swing.JPanel jPanelRemoveBranch;
    private javax.swing.JPanel jPanelVehicleTypes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBranchId;
    private javax.swing.JTextField jTextFieldFromDate;
    private javax.swing.JTextField jTextFieldToDate;
    private javax.swing.JLabel mainbg1;
    private javaswingdev.chart.PieChart pieChart1;
    private com.raven.swing.TextField tfAdminResponse;
    private com.raven.swing.TextField tfEmail2;
    private com.raven.swing.TextField tfInquiryID;
    private com.raven.swing.TextField tfMsgContent;
    private com.raven.swing.TextField tfMsgTitle;
    private com.raven.swing.TextField tfName2;
    private com.raven.swing.TextField tfUserInquiryID;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
